name: Daily Data Generation and Dispatch

on:
  schedule:
    # 每天北京时间 18:00 运行 (UTC+8)
    # 18:00 北京时间 = 10:00 UTC
    - cron: '0 10 * * *' # 北京时间每天 18:00 运行
  workflow_dispatch: # 允许手动触发，方便测试

jobs:
  generate_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 根据你的项目需求调整 Python 版本

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 假设 requirements.txt 在仓库根目录
        if [ -f requirements.txt ]; then
            pip install -r requirements.txt
        fi
        # 如果 merged_stock_analyzer.py 有其他未在 requirements.txt 中的依赖，请在此处添加
        pip install pandas openpyxl # 确保这些库已安装，因为它们通常用于处理 Excel

                - name: Check if today is a Chinese holiday
      id: check_holiday
      run: |
        echo "import datetime" > check_holiday.py
        echo "from chinesecalendar import is_holiday" >> check_holiday.py
        echo "" >> check_holiday.py
        echo "today = datetime.date.today()" >> check_holiday.py
        echo "if is_holiday(today):" >> check_holiday.py
        echo "    print('Today is a Chinese holiday. Skipping data generation.')" >> check_holiday.py
        echo "    print('is_holiday=true')" >> check_holiday.py
        echo "else:" >> check_holiday.py
        echo "    print('Today is not a Chinese holiday. Proceeding with data generation.')" >> check_holiday.py
        echo "    print('is_holiday=false')" >> check_holiday.py
        
        python check_holiday.py >> $GITHUB_OUTPUT

    - name: Skip if holiday
      if: steps.check_holiday.outputs.is_holiday == 'true'
      run: |
        echo "Skipping data generation as today is a Chinese holiday."
        exit 0

    - name: Run data generation script
      run: python merged_stock_analyzer.py
      # 确保 merged_stock_analyzer.py 会在当前目录下生成 stock_kline_data.xlsx

    - name: Upload stock_kline_data.xlsx as artifact
      uses: actions/upload-artifact@v4
      with:
        name: stock-kline-data
        path: stock_kline_data.xlsx
        retention-days: 1 # 数据保留一天，避免占用过多空间

    - name: Upload Data to Release for Manual Trigger
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest-data
        files: stock_kline_data.xlsx
        body: "Latest stock data for manual analysis runs."
        prerelease: false
        draft: false
        token: ${{ secrets.GITHUB_TOKEN }}
        replaces_artifacts: true

    - name: Dispatch event to Passive-Analysis
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT_TOKEN }} # 使用你创建的 PAT
        repository: cjbcmp/Passive-Analysis # 目标仓库
        event-type: stockdata-update # 事件类型，Passive-Analysis 将监听此类型
        client-payload: '{"repository": "${{ github.repository }}", "run_id": "${{ github.run_id }}"}'
