
name: Run Stock Analysis

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 22 * * 1-5' # 北京时间周一至周五早上6点运行

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 使用Python 3.10

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check if today is a Chinese holiday
      id: check_holiday
      run: |
        python -c "
import datetime
from chinesecalendar import is_holiday

today = datetime.date.today()
if is_holiday(today):
    print('Today is a Chinese holiday. Skipping analysis.')
    print('is_holiday=true')
else:
    print('Today is not a Chinese holiday. Proceeding with analysis.')
    print('is_holiday=false')
" >> $GITHUB_OUTPUT

    - name: Skip if holiday
      if: steps.check_holiday.outputs.is_holiday == 'true'
      run: |
        echo "Skipping analysis as today is a Chinese holiday."
        exit 0

    - name: Run script
      run: python merged_stock_analyzer.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: stock-analysis-results
        path: |
          *.xlsx
        retention-days: 1
