
name: Run Stock Analysis

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 22 * * *' # 每天的22:00 UTC (北京时间早上6点)运行

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 使用Python 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run script
      run: python merged_stock_analyzer.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: stock-analysis-results
        path: |
          *.xlsx
